### ISSUE TITLE
feature request: consider all PR commits after the first an autosquash commit

### ISSUE THREAD

**Issue by stevedlawrence** [xt0rted/block-autosquash-commits-action#54]
We have a use case where we consider every commit of a pull request after the first one an autosquash commit, regardless if it has !fixup or !squash. The idea here is we want each pull request to only have a single associated commit, and it is difficult for us to enforce that pull requests always use --fixup or --squash correctly.

Thoughts on adding an optional parameter that changes the behavior so that if a pull request has more than one commit, regardless if it contains !fixup or !squash, that too is considered an error and they must be squashed?

**Comment by adrianschmidt** [comment]
I think that feels more like separate functionality than something that belongs in this action. Isn't there already some action that checks if there are more than one commit in the PR?

Or change the repo settings to only allow **Squash and merge** (although I can see how that doesn't necessarily achieve what you need)?

**Comment by stevedlawrence** [comment]
That's fair. This was the closest thing I could find at the time, but you're probably right, this feature probably doesn't belong here. And the lack of any update in 2 years probably confirms that. I'll close this request.

Though, I haven't been able to find an action that does what I'm looking for so far, if you know of one I'd love to hear about it.

We don't like "squash and merge" in our project for a couple reasons:
1. With squash an merge, it creates a merge commit for every squashed and merged PR, which makes the git history significantly more messy without really adding anything of value
2. With squash and merge, the person that merges a PR is responsible for creating the new squashed commit message when they merge it. But we find that the PR author has a better idea of the changes in the PR and so can more easily make a better commit message

**Comment by adrianschmidt** [comment]
> That's fair. This was the closest thing I could find at the time, but you're probably right, this feature probably doesn't belong here. And the lack of any update in 2 years probably confirms that. I'll close this request.
> 
> Though, I haven't been able to find an action that does what I'm looking for so far, if you know of one I'd love to hear about it.

I did a quick search before posting, and didn't find anything either. It seems like it ought to be a pretty easy thing to write though… 🤔
 
> We don't like "squash and merge" in our project for a couple reasons:
> 
> 1. With squash an merge, it creates a merge commit for every squashed and merged PR, which makes the git history significantly more messy without really adding anything of value
> 2. With squash and merge, the person that merges a PR is responsible for creating the new squashed commit message when they merge it. But we find that the PR author has a better idea of the changes in the PR and so can more easily make a better commit message

Yeah, I suspected these were the reason for not using "squash and merge".

**Comment by stevedlawrence** [comment]
> It seems like it ought to be a pretty easy thing to write though… thinking

Agreed, just need to to find the time...

**Comment by adrianschmidt** [comment]
> > It seems like it ought to be a pretty easy thing to write though… thinking
> 
> Agreed, just need to to find the time...

Tell me about it 😅

**Comment by xt0rted** [comment]
Sorry for missing this issue @stevedlawrence. The feature request is out of scope of this action but I'll certainly create a new one that does this. For the time being you can get the required behavior with the following workflow:

```yaml
on:
  pull_request:

permissions:
  pull-requests: read

jobs:
  commit-check:
    name: Fail if more than 1 commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            const commits = await github.pulls.listCommits({
                ...context.repo,
                pull_number: context.issue.number,
            });

            if (commits.data.length) {
                core.error("This pull request needs to be squashed to 1 commit before it can be merged");
            }
```
